name: Export CCX Image

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Pull CCX image and export
        run: |
          docker pull crpi-i19l8zl0ugidq97v.cn-hangzhou.personal.cr.aliyuncs.com/bene/ccx:latest
          docker save -o ccx.tar crpi-i19l8zl0ugidq97v.cn-hangzhou.personal.cr.aliyuncs.com/bene/ccx:latest

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ccx-image
          path: ccx.tar
          retention-days: 7
